---
extends: default

ignore: |
  .generated/
  .venv/
  inventories/*/group_vars/*/vault.yml
  inventories/*/host_vars/*/vault.yml

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  line-length:
    max: 140
    level: warning
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy: disable
