---
- name: Reset Kubernetes with Kubespray
  ansible.builtin.command:
    argv:
      - "{{ kubespray_control_venv_dir }}/bin/ansible-playbook"
      - --forks
      - "{{ kubespray_control_cluster_playbook_forks | string }}"
      - -i
      - "{{ kubespray_control_inventory_dir }}/inventory.ini"
      - --private-key
      - "{{ kubespray_control_private_key_file }}"
      - reset.yml
      - -b
      - "{{ kubespray_control_cluster_playbook_verbosity }}"
      - -e
      - reset_confirmation=yes
    chdir: "{{ kubespray_control_install_dir }}"
  environment: "{{ kubespray_control_reset_environment }}"
  no_log: "{{ kubespray_control_enable_deploy_output_hidden | bool }}"
  register: kubespray_control_reset_result
  changed_when: true
  when:
    - kubespray_control_enable_reset_playbook_run | bool
    - kubespray_control_enable_cluster_reset | bool
