---
all:
  children:
    control_node:
      hosts:
        localhost:
          ansible_connection: local

    vmware_esxi:
      hosts:
        vm_esxi_8.0:
          ansible_connection: local
        vm_esxi_6.7:
          ansible_connection: local

    kube_control_plane:
      hosts:
        ubuntu_24.04-mgmt-01:
        ubuntu_24.04-mgmt-02:
        ubuntu_24.04-mgmt-03:

    kube_node:
      hosts:
        ubuntu_24.04-wrk-01:
        ubuntu_24.04-wrk-02:
        ubuntu_24.04-wrk-03:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

    managed_vms:
      hosts:
        ubuntu_24.04-mgmt-01:
          ansible_host: 172.16.6.20
          kubernetes_primary_interface: ens33

        ubuntu_24.04-mgmt-02:
          ansible_host: 172.16.6.21
          kubernetes_primary_interface: ens192

        ubuntu_24.04-mgmt-03:
          ansible_host: 172.16.6.22
          kubernetes_primary_interface: ens192

        ubuntu_24.04-wrk-01:
          ansible_host: 172.16.6.23
          kubernetes_primary_interface: ens33

        ubuntu_24.04-wrk-02:
          ansible_host: 172.16.6.24
          kubernetes_primary_interface: ens33

        ubuntu_24.04-wrk-03:
          ansible_host: 172.16.6.25
          kubernetes_primary_interface: ens33

    longhorn_nodes:
      hosts:
        ubuntu_24.04-wrk-01:
        ubuntu_24.04-wrk-02:
        ubuntu_24.04-wrk-03:

    discovered_managed_vms:
      hosts: {}
