---
- name: Validate ESXi production variables
  hosts: vmware_esxi
  gather_facts: false
  roles:
    - esxi_validate

- name: Gather ESXi host facts
  hosts: vmware_esxi
  gather_facts: false
  roles:
    - esxi_facts

- name: Power VM on standalone ESXi
  hosts: vm_esxi_8.0
  gather_facts: false
  roles:
    - vm_power
