---
- import_playbook: 00-control-node.yml

- import_playbook: 04-vm-power-all.yml
  vars:
    vm_state: powered-on

- import_playbook: site-guest.yml

- import_playbook: 10-kubernetes-node-prepare.yml

- import_playbook: 09-kubespray-deploy.yml
